In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("..\data\investments_VC.csv")

In [3]:
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0,0,0,0,0,0,0,0,0,0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0,0,0,0,0,0,0,0,0,0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0,0,0,0,0,0,0,0,0,0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0,0,0,0,0,0,0,0,0,0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49438 entries, 0 to 49437
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             49438 non-null  str
 1   name                  49437 non-null  str
 2   homepage_url          45989 non-null  str
 3   category_list         45477 non-null  str
 4    market               45470 non-null  str
 5   funding_total_usd     49438 non-null  str
 6   status                48124 non-null  str
 7   country_code          44165 non-null  str
 8   state_code            30161 non-null  str
 9   region                44165 non-null  str
 10  city                  43322 non-null  str
 11  funding_rounds        49438 non-null  int64
 12  founded_at            38554 non-null  str
 13  founded_month         38482 non-null  str
 14  founded_quarter       38482 non-null  str
 15  founded_year          38482 non-null  float64
 16  first_funding_at      49438 non-null  str
 17  last_funding_at       49438 non-null  str
 18  seed                  49438 non-null  int64
 19  venture               49438 non-null  int64
 20  equity_crowdfunding   49438 non-null  int64
 21  undisclosed           49438 non-null  int64
 22  convertible_note      49438 non-null  int64
 23  debt_financing        49438 non-null  int64
 24  angel                 49438 non-null  int64
 25  grant                 49438 non-null  int64
 26  private_equity        49438 non-null  int64
 27  post_ipo_equity       49438 non-null  int64
 28  post_ipo_debt         49438 non-null  int64
 29  secondary_market      49438 non-null  int64
 30  product_crowdfunding  49438 non-null  int64
 31  round_A               49438 non-null  int64
 32  round_B               49438 non-null  int64
 33  round_C               49438 non-null  int64
 34  round_D               49438 non-null  int64
 35  round_E               49438 non-null  int64
 36  round_F               49438 non-null  int64
 37  round_G               49438 non-null  int64
 38  round_H               49438 non-null  int64
dtypes: float64(1), int64(22), str(16)
memory usage: 14.7 MB

## Drop Values

In [5]:
drop_cols = [
    'permalink',
    'name',
    'homepage_url'
]

df.drop(columns=drop_cols, inplace=True)

## Missing Values in Columns

In [6]:
missing = (
    df.isnull()
      .sum()
      .to_frame("Missing Values")
)

missing["Percentage"] = (
    missing["Missing Values"] / len(df)
) * 100

missing.sort_values("Percentage", ascending=False)

                      Missing Values  Percentage
state_code                     19277   38.992273
founded_year                   10956   22.161091
founded_quarter                10956   22.161091
founded_month                  10956   22.161091
founded_at                     10884   22.015454
city                            6116   12.371051
region                          5273   10.665885
country_code                    5273   10.665885
 market                         3968    8.026215
category_list                   3961    8.012056
status                          1314    2.657875
funding_total_usd                  0    0.000000
funding_rounds                     0    0.000000
first_funding_at                   0    0.000000
last_funding_at                    0    0.000000
seed                               0    0.000000
venture                            0    0.000000
equity_crowdfunding                0    0.000000
undisclosed                        0    0.000000
convertible_note                   0    0.000000
debt_financing                     0    0.000000
angel                              0    0.000000
grant                              0    0.000000
private_equity                     0    0.000000
post_ipo_equity                    0    0.000000
post_ipo_debt                      0    0.000000
secondary_market                   0    0.000000
product_crowdfunding               0    0.000000
round_A                            0    0.000000
round_B                            0    0.000000
round_C                            0    0.000000
round_D                            0    0.000000
round_E                            0    0.000000
round_F                            0    0.000000
round_G                            0    0.000000
round_H                            0    0.000000

## Handle Target Column

In [7]:
unknown_df = df[df['status'].isna()].copy()

df = df[df['status'].isin(['acquired', 'closed'])].copy()

In [8]:
# Remove leading and trailing whitespaces from all column names
df.columns = df.columns.str.strip()

In [9]:
df['funding_total_usd'] = (
    df['funding_total_usd']
      .replace('-', np.nan)
      .str.replace(',', '', regex=False)
)

df['funding_total_usd'] = pd.to_numeric(
    df['funding_total_usd'],
    errors='coerce'
)

## Convert Date Column

In [34]:
date_cols = [
    'founded_at',
    'first_funding_at',
    'last_funding_at'
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

## Verify Categorical Data

In [11]:
for col in [
    'market',
    'country_code',
    'state_code'
]:
    print(df[col].nunique())

407
67
56

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 6295 entries, 0 to 49430
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   category_list         6066 non-null   str
 1   market                6064 non-null   str
 2   funding_total_usd     5376 non-null   float64
 3   status                6295 non-null   str
 4   country_code          5667 non-null   str
 5   state_code            4417 non-null   str
 6   region                5667 non-null   str
 7   city                  5604 non-null   str
 8   funding_rounds        6295 non-null   int64
 9   founded_at            4530 non-null   datetime64[us]
 10  founded_month         4967 non-null   str
 11  founded_quarter       4967 non-null   str
 12  founded_year          4967 non-null   float64
 13  first_funding_at      6295 non-null   datetime64[us]
 14  last_funding_at       6295 non-null   datetime64[us]
 15  seed                  6295 non-null   int64
 16  venture               6295 non-null   int64
 17  equity_crowdfunding   6295 non-null   int64
 18  undisclosed           6295 non-null   int64
 19  convertible_note      6295 non-null   int64
 20  debt_financing        6295 non-null   int64
 21  angel                 6295 non-null   int64
 22  grant                 6295 non-null   int64
 23  private_equity        6295 non-null   int64
 24  post_ipo_equity       6295 non-null   int64
 25  post_ipo_debt         6295 non-null   int64
 26  secondary_market      6295 non-null   int64
 27  product_crowdfunding  6295 non-null   int64
 28  round_A               6295 non-null   int64
 29  round_B               6295 non-null   int64
 30  round_C               6295 non-null   int64
 31  round_D               6295 non-null   int64
 32  round_E               6295 non-null   int64
 33  round_F               6295 non-null   int64
 34  round_G               6295 non-null   int64
 35  round_H               6295 non-null   int64
dtypes: datetime64[us](3), float64(2), int64(22), str(9)
memory usage: 1.8 MB

In [13]:
# Converts 2026.0 to "2026" and leaves NaN empty
df['founded_year'] = df['founded_year'].astype('Int64').astype(str).str.replace('<NA>', '')

In [14]:
df.describe()

,funding_total_usd,funding_rounds,founded_at,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
count,5.376000e+03,6295.000000,4530,6295,6295,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,...,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,6.295000e+03,6295.0
mean,1.765471e+07,1.774106,2004-12-15 10:53:52.847682,2008-07-26 03:10:05.623510,2009-07-28 21:50:04.098490,1.631236e+05,1.028132e+07,1.411129e+03,1.069192e+05,7.953678e+03,...,1.311166e+03,4.332010e+02,1.715407e+06,2.511356e+06,1.873205e+06,1.020213e+06,3.939582e+05,1.601970e+05,2.152502e+04,0.0
min,1.000000e+03,1.000000,1911-01-01 00:00:00,1960-01-01 00:00:00,1960-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
25%,8.417548e+05,1.000000,2002-01-01 00:00:00,2006-11-07 00:00:00,2008-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
50%,4.500000e+06,1.000000,2006-08-26 00:00:00,2008-11-10 00:00:00,2010-01-04 00:00:00,0.000000e+00,1.507400e+06,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
75%,1.550000e+07,2.000000,2009-01-10 00:00:00,2010-10-26 00:00:00,2011-08-27 00:00:00,0.000000e+00,1.100000e+07,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,1.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
max,5.700000e+09,15.000000,2014-01-07 00:00:00,2014-12-01 00:00:00,2014-12-01 00:00:00,2.500000e+07,7.750000e+08,5.500000e+06,1.250000e+08,1.352014e+07,...,7.343789e+06,2.400000e+06,2.250000e+08,3.500000e+08,2.000000e+08,2.500000e+08,2.200000e+08,2.860000e+08,6.300000e+07,0.0
std,9.349786e+07,1.270575,NaN,NaN,NaN,7.585670e+05,2.462916e+07,7.653789e+04,2.063324e+06,2.021176e+05,...,9.301513e+04,3.048581e+04,6.324256e+06,8.937786e+06,7.681419e+06,7.738509e+06,4.574904e+06,4.333989e+06,1.033467e+06,0.0

In [15]:
df[df['funding_rounds'] < 0]

Empty DataFrame
Columns: [category_list, market, funding_total_usd, status, country_code, state_code, region, city, funding_rounds, founded_at, founded_month, founded_quarter, founded_year, first_funding_at, last_funding_at, seed, venture, equity_crowdfunding, undisclosed, convertible_note, debt_financing, angel, grant, private_equity, post_ipo_equity, post_ipo_debt, secondary_market, product_crowdfunding, round_A, round_B, round_C, round_D, round_E, round_F, round_G, round_H]
Index: []

[0 rows x 36 columns]

In [16]:
df[(df['funding_rounds'] == 0) &
   (df['funding_total_usd'] > 0)]

Empty DataFrame
Columns: [category_list, market, funding_total_usd, status, country_code, state_code, region, city, funding_rounds, founded_at, founded_month, founded_quarter, founded_year, first_funding_at, last_funding_at, seed, venture, equity_crowdfunding, undisclosed, convertible_note, debt_financing, angel, grant, private_equity, post_ipo_equity, post_ipo_debt, secondary_market, product_crowdfunding, round_A, round_B, round_C, round_D, round_E, round_F, round_G, round_H]
Index: []

[0 rows x 36 columns]

In [17]:
df[(df['funding_total_usd'] == 0) &
   (df['funding_rounds'] > 0)]

Empty DataFrame
Columns: [category_list, market, funding_total_usd, status, country_code, state_code, region, city, funding_rounds, founded_at, founded_month, founded_quarter, founded_year, first_funding_at, last_funding_at, seed, venture, equity_crowdfunding, undisclosed, convertible_note, debt_financing, angel, grant, private_equity, post_ipo_equity, post_ipo_debt, secondary_market, product_crowdfunding, round_A, round_B, round_C, round_D, round_E, round_F, round_G, round_H]
Index: []

[0 rows x 36 columns]

In [18]:
df[df['first_funding_at'] < df['founded_at']]

,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
20,|Curated Web|,Curated Web,2535000.0,acquired,USA,CA,SF Bay Area,San Francisco,2,2010-01-07,...,0,0,2520000,0,0,0,0,0,0,0
310,|Loyalty Programs|Social Media|E-Commerce|Ente...,E-Commerce,12900000.0,acquired,USA,CA,SF Bay Area,San Francisco,6,2010-01-01,...,0,0,4500000,5000000,0,0,0,0,0,0
475,|Sensors|Networking|Wireless|Software|,Software,15000.0,closed,NaN,NaN,NaN,NaN,1,2011-05-03,...,0,0,0,0,0,0,0,0,0,0
505,|Search|,Search,6000000.0,acquired,USA,CA,SF Bay Area,San Francisco,2,2007-01-07,...,0,0,5250000,0,0,0,0,0,0,0
537,|Advertising|,Advertising,25000.0,closed,IND,NaN,Chandigarh,Chandigarh,1,2007-05-12,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49174,|Music|Games|,Music,26000000.0,acquired,USA,CA,SF Bay Area,Mountain View,2,2007-01-06,...,0,0,13000000,0,13000000,0,0,0,0,0
49195,|Postal and Courier Services|Public Relations|,Postal and Courier Services,15000.0,closed,USA,AZ,Phoenix,Peoria,1,2008-11-10,...,0,0,0,0,0,0,0,0,0,0
49226,|Publishing|,Publishing,2000000.0,acquired,USA,CA,SF Bay Area,San Francisco,1,2011-09-03,...,0,0,0,0,0,0,0,0,0,0
49227,|Fashion|Sales and Marketing|Marketplaces|B2B|...,Fashion,NaN,acquired,DEU,NaN,Cologne,Cologne,1,2012-01-01,...,0,0,0,0,0,0,0,0,0,0
49328,|E-Commerce|Chat|Messaging|,Chat,392000.0,acquired,SGP,NaN,Singapore,Singapore,3,2008-01-01,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df[df['last_funding_at'] < df['first_funding_at']]

Empty DataFrame
Columns: [category_list, market, funding_total_usd, status, country_code, state_code, region, city, funding_rounds, founded_at, founded_month, founded_quarter, founded_year, first_funding_at, last_funding_at, seed, venture, equity_crowdfunding, undisclosed, convertible_note, debt_financing, angel, grant, private_equity, post_ipo_equity, post_ipo_debt, secondary_market, product_crowdfunding, round_A, round_B, round_C, round_D, round_E, round_F, round_G, round_H]
Index: []

[0 rows x 36 columns]

In [20]:
df[df['last_funding_at'] < df['first_funding_at']]

Empty DataFrame
Columns: [category_list, market, funding_total_usd, status, country_code, state_code, region, city, funding_rounds, founded_at, founded_month, founded_quarter, founded_year, first_funding_at, last_funding_at, seed, venture, equity_crowdfunding, undisclosed, convertible_note, debt_financing, angel, grant, private_equity, post_ipo_equity, post_ipo_debt, secondary_market, product_crowdfunding, round_A, round_B, round_C, round_D, round_E, round_F, round_G, round_H]
Index: []

[0 rows x 36 columns]

In [21]:
df.loc[
    df['first_funding_at'] < df['founded_at'],
    ['founded_at', 'first_funding_at', 'last_funding_at',
     'founded_year', 'funding_rounds', 'funding_total_usd']
].head(20)

,founded_at,first_funding_at,last_funding_at,founded_year,funding_rounds,funding_total_usd
20,2010-01-07,2010-01-01,2011-02-16,2010,2,2535000.0
310,2010-01-01,2009-12-15,2013-03-12,2010,6,12900000.0
475,2011-05-03,2011-03-05,2011-03-05,2011,1,15000.0
505,2007-01-07,2007-01-01,2008-10-01,2007,2,6000000.0
537,2007-05-12,2007-01-05,2007-01-05,2007,1,25000.0
650,2008-01-08,2008-01-01,2009-12-04,2008,7,457282.0
932,2005-01-11,2005-01-01,2008-01-23,2005,3,17600000.0
939,2009-01-04,2009-01-01,2009-01-01,2009,1,NaN
1007,2010-01-12,2010-01-01,2011-04-15,2010,2,54493.0
1069,2006-08-08,2006-08-01,2007-04-18,2006,2,27000000.0
1258,2009-01-01,2008-03-18,2008-03-18,2009,1,13000000.0
1407,2006-01-01,1999-10-01,2002-01-01,2006,2,85000000.0
1467,2000-01-01,1998-01-01,1998-01-01,2000,1,NaN
1497,2006-01-03,2005-01-01,2013-04-01,2006,8,74311925.0
1921,2011-01-06,2011-01-01,2011-01-01,2011,1,NaN
2055,2011-01-01,2010-11-02,2011-08-01,2011,3,250000.0
2291,2011-04-07,2007-08-01,2009-10-08,2011,2,3900000.0
2302,2010-01-01,2006-08-28,2006-08-28,2010,1,16000000.0
2572,2011-10-09,2011-09-01,2012-03-01,2011,2,160000.0
3005,2011-11-01,2011-01-11,2012-05-10,2011,2,1000000.0

In [22]:
gap = (df["founded_at"] - df["first_funding_at"]).dt.days

gap[gap > 365].describe()

count       69.000000
mean      1084.710145
std       2102.784233
min        366.000000
25%        427.000000
50%        682.000000
75%       1096.000000
max      17653.000000
dtype: float64

In [23]:
df.loc[
    gap > 365 * 5,
    [
        "status",
        "founded_at",
        "first_funding_at",
        "last_funding_at",
        "funding_rounds",
        "funding_total_usd"
    ]
]

,status,founded_at,first_funding_at,last_funding_at,funding_rounds,funding_total_usd
1407,acquired,2006-01-01,1999-10-01,2002-01-01,2,85000000.0
9590,closed,2012-06-06,2007-06-01,2007-06-01,1,15000.0
13573,acquired,2007-01-01,1999-09-02,2012-12-03,5,33052663.0
17676,closed,2009-03-11,2004-01-01,2004-01-01,1,1000000.0
22250,closed,2008-05-01,1960-01-01,1960-01-01,1,NaN
44017,acquired,2011-01-01,2003-01-01,2010-10-19,3,30500000.0

##### During data validation, 447 companies were identified where the first recorded funding date preceded the recorded founding date. Most discrepancies were within one year and are plausibly explained by pre-incorporation funding or differences between operational founding and legal incorporation. However, 12 companies exhibited gaps exceeding five years. These records were treated as anomalous and excluded from further analysis due to likely data quality issues.

In [24]:
gap.sort_values(ascending=False).head(6)

22250    17653.0
44017     2922.0
13573     2678.0
1407      2284.0
17676     1896.0
9590      1832.0
dtype: float64

In [25]:
gap_last = (df["founded_at"] - df["last_funding_at"]).dt.days

In [26]:
df.loc[
    gap_last > 365 * 5,
    [
        "status",
        "founded_at",
        "first_funding_at",
        "last_funding_at",
        "funding_rounds",
        "funding_total_usd"
    ]
]

,status,founded_at,first_funding_at,last_funding_at,funding_rounds,funding_total_usd
9590,closed,2012-06-06,2007-06-01,2007-06-01,1,15000.0
17676,closed,2009-03-11,2004-01-01,2004-01-01,1,1000000.0
22250,closed,2008-05-01,1960-01-01,1960-01-01,1,NaN

### Remove above rows

In [27]:
invalid_temporal = (
    (df["funding_rounds"] == 1) &
    (df["first_funding_at"] == df["last_funding_at"]) &
    ((df["founded_at"] - df["first_funding_at"]).dt.days > 365 * 5)
)

anomalies_df = df.loc[invalid_temporal].copy()

In [28]:
df = df.drop(df.loc[invalid_temporal].index).reset_index(drop=True)

In [ ]:
df.to_csv("..\data\investments_VC_new.csv", index=False)